LinkLuaModifier("modifier_stunned_lua", "abilities/modifier_stunned", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_silence_lua", "abilities/modifier_silence_lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_knockback_lua", "abilities/modifier_knockback", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_charges", "abilities/modifier_charges", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hidden", "abilities/modifier_hidden", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_falling", "abilities/modifier_falling", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero", "abilities/modifier_hero", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_tower", "abilities/modifier_tower", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_creep", "abilities/modifier_creep", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_preview", "abilities/modifier_preview", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damaged", "abilities/modifier_damaged", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_launched", "abilities/modifier_launched", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wearable_visuals", "abilities/modifier_wearable_visuals", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wearable_visuals_status_fx", "abilities/modifier_wearable_visuals", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wearable_visuals_hero_fx", "abilities/modifier_wearable_visuals", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_wearable_visuals_activity", "abilities/modifier_wearable_visuals", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_attack_speed", "abilities/modifier_attack_speed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_healthbar", "abilities/modifier_custom_healthbar", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_player_id", "abilities/modifier_player_id", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_obstacle", "abilities/modifier_obstacle", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_tree_heal", "abilities/modifier_tree_heal", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_rune_blue", "abilities/modifier_rune_blue", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier( "modifier_animation", "lib/modifiers/modifier_animation.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_animation_translate", "lib/modifiers/modifier_animation_translate.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_animation_translate_permanent", "lib/modifiers/modifier_animation_translate_permanent.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier( "modifier_animation_freeze", "lib/modifiers/modifier_animation_freeze.lua", LUA_MODIFIER_MOTION_NONE )

LinkLuaModifier("modifier_jugger_sword", "abilities/jugger/modifier_jugger_sword", LUA_MODIFIER_MOTION_NONE)